shared:
    image: node:8

jobs:
    main:
        requires: [~pr, ~commit]
        steps:
            - init: npm install
            - test: npm test
    publish:
        requires: [main]
        steps:
            - install: npm install semantic-release
            - publish: npm run semantic-release
        secrets:
            # Publishing to NPM
            - NPM_TOKEN
            # Pushing tags to Git
            - GH_TOKEN
